# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20171005_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='link',
            field=models.TextField(blank=True),
        ),
    ]
