# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-05 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_note_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
